apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cassandra-api-autoscaler
  namespace: disloman
  labels:
    app: disloman
    name: cassandra-api-autoscaler
    type: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: cassandra-api-microservice
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80