apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: disloman
  labels:
    app: disloman
    name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
